# -*- coding: utf-8 -*-
"""从 Edge 抓取 bilibili 登录 Cookie → cookies.txt

原理:
  1. 以调试端口(9222)启动一个独立的 Edge 实例(独立 user-data-dir,不影响日常 Edge)
  2. 打开 B 站首页,通过 CDP(Chrome DevTools Protocol)轮询页面 cookie
  3. 等到出现 SESSDATA(用户扫码/登录后自动出现),写成 yt-dlp 能用的 Netscape 格式

安全: 生成的 cookies.txt 含登录凭证,只写在本机,绝不入库/入包。
"""
import json
import os
import subprocess
import time
import urllib.parse
import urllib.request

CDP_PORT = 9222
BILI_HOME = "https://www.bilibili.com/"
LOGIN_WAIT_SECONDS = 180
KEY_COOKIES = ("SESSDATA", "bili_jct", "DedeUserID")

CREATE_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)


def find_edge_exe():
    """在常见安装位置找 msedge.exe,找不到返回 None"""
    candidates = [
        os.path.expandvars(r"%ProgramFiles(x86)%\Microsoft\Edge\Application\msedge.exe"),
        os.path.expandvars(r"%ProgramFiles%\Microsoft\Edge\Application\msedge.exe"),
        os.path.expandvars(r"%LocalAppData%\Microsoft\Edge\Application\msedge.exe"),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def _http_json(url, timeout=5):
    with urllib.request.urlopen(url, timeout=timeout) as resp:
        return json.load(resp)


def is_cdp_running():
    """9222 端口上是否已有 Edge 调试服务"""
    try:
        _http_json(f"http://127.0.0.1:{CDP_PORT}/json/version", timeout=2)
        return True
    except Exception:
        return False


def start_debug_edge(log):
    """启动一个带调试端口的独立 Edge(独立 profile,不干扰日常 Edge)"""
    edge = find_edge_exe()
    if not edge:
        return False, "未找到 Edge 浏览器,请先安装 Microsoft Edge"
    profile = os.path.join(os.environ.get("TEMP", "."), "bili_dl_edge_profile")
    os.makedirs(profile, exist_ok=True)
    subprocess.Popen(
        [
            edge,
            f"--remote-debugging-port={CDP_PORT}",
            f"--user-data-dir={profile}",
            "--no-first-run",
            "--no-default-browser-check",
            "--new-window",
            BILI_HOME,
        ],
        creationflags=CREATE_NO_WINDOW,
    )
    for _ in range(120):  # 最多等 60 秒
        if is_cdp_running():
            return True, ""
        time.sleep(0.5)
    return False, "Edge 调试端口启动超时(60秒),请检查是否被杀毒软件拦截"


def _pick_bili_tab():
    """挑一个 B 站页面标签,没有就新建"""
    targets = _http_json(f"http://127.0.0.1:{CDP_PORT}/json", timeout=5)
    for t in targets:
        if t.get("type") == "page" and "bilibili.com" in t.get("url", ""):
            return t["webSocketDebuggerUrl"]
    url = "http://127.0.0.1:%d/json/new?%s" % (CDP_PORT, urllib.parse.quote(BILI_HOME))
    with urllib.request.urlopen(url, timeout=5) as resp:
        return json.load(resp)["webSocketDebuggerUrl"]


def _grab_from_cdp(log, need_login):
    """连上 B 站标签,轮询等待 SESSDATA 出现,返回 bilibili cookie 列表(没等到返回 None)"""
    import websocket

    ws_url = _pick_bili_tab()
    ws = websocket.create_connection(ws_url, timeout=30)
    msg_id = 0

    def call(method, params=None):
        nonlocal msg_id
        msg_id += 1
        payload = {"id": msg_id, "method": method, "params": params or {}}
        ws.send(json.dumps(payload))
        while True:
            resp = json.loads(ws.recv())
            if resp.get("id") == msg_id:
                return resp

    deadline = time.time() + LOGIN_WAIT_SECONDS
    last_note = 0.0
    try:
        while time.time() < deadline:
            resp = call("Network.getAllCookies")
            if "error" in resp:
                resp = call("Storage.getCookies")
            cookies = resp.get("result", {}).get("cookies", [])
            bili = [c for c in cookies if "bilibili.com" in c.get("domain", "")]
            sess = next((c for c in bili if c["name"] == "SESSDATA" and c.get("value")), None)
            if sess:
                return bili
            if need_login and time.time() - last_note > 6:
                need_login()
                last_note = time.time()
            time.sleep(3)
    finally:
        ws.close()
    return None


def write_netscape_cookies(cookies, path):
    """写成 yt-dlp 可读的 Netscape cookies.txt"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by BiliHDDownloader via Edge CDP",
        "# 本文件包含 B 站登录凭证,仅限本机使用,切勿外传/上传",
    ]
    for c in cookies:
        # CDP 的 domain 带点(如 .bilibili.com)= 域cookie → TRUE 且保留点
        # 不带点(如 bilibili.com) = host-only → FALSE
        # 必须遵守 http.cookiejar 的断言: 第二列 TRUE ⟺ 域名以 . 开头
        raw = c["domain"]
        if raw.startswith("."):
            domain, domain_flag = raw, "TRUE"
        else:
            domain, domain_flag = raw, "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        http_only = "TRUE" if c.get("httpOnly") else "FALSE"
        expires = int(c.get("expires", 0) or 0)
        lines.append(
            "%s\t%s\t%s\t%s\t%d\t%s\t%s"
            % (domain, domain_flag, c.get("path", "/"), secure, expires, c["name"], c["value"])
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def grab_bili_cookie(cookie_path, log=print, need_login=None):
    """主入口:返回 (成功bool, 信息str)。cookie_path 为要写出的 cookies.txt 路径"""
    if not is_cdp_running():
        ok, msg = start_debug_edge(log)
        if not ok:
            return False, msg
    try:
        log("已连接 Edge,等待 B 站页面...")
        time.sleep(4)
        cookies = _grab_from_cdp(log, need_login)
        if cookies is None:
            return False, "等待登录超时(%d秒)。请确认在弹出的 Edge 窗口里完成了登录后重试" % LOGIN_WAIT_SECONDS
        bili = [c for c in cookies if "bilibili.com" in c.get("domain", "")]
        write_netscape_cookies(bili, cookie_path)
        sess = next((c for c in bili if c["name"] == "SESSDATA"), None)
        names = sorted({c["name"] for c in bili})
        has_login = bool(sess and sess.get("value"))
        if has_login:
            info = "抓取成功:共 %d 个 bilibili cookie,已写入 %s" % (len(bili), cookie_path)
        else:
            info = "抓取完成但缺少 SESSDATA(未登录),请在弹出的 Edge 窗口登录后重试"
        return True, info
    except Exception as e:
        return False, "抓取 Cookie 失败:%s" % e
